name: 'Citra Docker Image CI'
on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: ["linux-appimage", "linux-fresh"]
    
    steps:
    - uses: actions/checkout@v3
    - uses: docker/setup-buildx-action@v2
      name: Setup Docker BuildX system
    - name: Login to DockerHub
      uses: docker/login-action@v2
      if: (github.ref == 'refs/heads/master') && (github.repository == 'PabloMK7/build-environments')
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: docker/build-push-action@v4
      name: Build image
      with:
        push: ${{ (github.ref == 'refs/heads/master') && (github.repository == 'PabloMK7/build-environments') }}
        context: ${{ matrix.image }}
        tags: pablomk7/build-environments:${{ matrix.image }}
